# Change these first
owner: d35k # Your GitHub username
repo: uptime-bot # Your GitHub repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Eczazone
    url: https://eczazone.com
  - name: Dermazone
    url: https://dermazone.org
  - name: KBBZone
    url: https://kbbzone.com
  - name: KVCZone
    url: https://kvczone.com
  - name: Psikezone
    url: https://psikezone.com
  - name: Ortopedizone
    url: https://ortopedizone.com
  - name: FTRZone
    url: https://ftrzone.com
  - name: Norozone
    url: https://norozone.com
assignees:
  - d35k
  - jnbn
status-website:
  baseUrl: /uptime-bot # where "repo" is your repository name
  logoUrl: https://epigra.com/themes/epigra-2017/assets/images/logo.svg
  name: Epigra Test Uptime Bot
  introTitle: "**Epigra** is İstanbul based full service digital agency with a deep passion in helping clients to achieve great results and make their brands grow"
  introMessage: This website is only testing for new features of Upptime bot to compare other services such as uptimebot.

